// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

namespace StockBoard.Function.Simulator.StockBoardServiceClient.Models
{
    public partial class BrokerViewModel
    {
        /// <summary>
        /// Initializes a new instance of the BrokerViewModel class.
        /// </summary>
        public BrokerViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BrokerViewModel class.
        /// </summary>
        public BrokerViewModel(System.Guid? id = default(System.Guid?), string name = default(string), IList<PersonViewModel> persons = default(IList<PersonViewModel>), IList<OrderViewModel> orders = default(IList<OrderViewModel>))
        {
            Id = id;
            Name = name;
            Persons = persons;
            Orders = orders;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "persons")]
        public IList<PersonViewModel> Persons { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orders")]
        public IList<OrderViewModel> Orders { get; set; }

    }
}
