// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

namespace StockBoard.Function.Simulator.StockBoardServiceClient.Models
{
    public partial class PersonViewModel
    {
        /// <summary>
        /// Initializes a new instance of the PersonViewModel class.
        /// </summary>
        public PersonViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PersonViewModel class.
        /// </summary>
        public PersonViewModel(System.Guid? id = default(System.Guid?), string name = default(string), IList<OrderViewModel> orders = default(IList<OrderViewModel>))
        {
            Id = id;
            Name = name;
            Orders = orders;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orders")]
        public IList<OrderViewModel> Orders { get; set; }

    }
}
